/**
 * Normalized events. Everything host-specific is translated into these shapes by the plugin
 * adapter or the importer; the repository and analytics never see raw OpenCode structures.
 */

export type Origin = "plugin" | "import"

export type CostSource = "host_computed" | "provider_reported" | "unavailable"

export type ProjectEvent = {
  kind: "project"
  id: string
  worktree: string | null
  vcs: string | null
  ts: number
}

export type SessionEvent = {
  kind: "session"
  id: string
  projectId: string | null
  parentId: string | null
  directory: string | null
  agent: string | null
  hostVersion: string | null
  configFingerprint: string | null
  createdAt: number | null
  updatedAt: number | null
}

export type MessageEvent = {
  kind: "message"
  id: string
  sessionId: string
  role: "user" | "assistant"
  parentMessageId: string | null
  agent: string | null
  provider: string | null
  model: string | null
  createdAt: number | null
  completedAt: number | null
  finish: string | null
  error: string | null
}

/** A user message turned out to be synthetic (generated by OpenCode, not typed by the user). */
export type SyntheticMarkEvent = {
  kind: "synthetic_mark"
  messageId: string
  sessionId: string
}

export type ModelUsageEvent = {
  kind: "step"
  /** Dedup key: the id of OpenCode's step-finish part. */
  id: string
  sessionId: string
  messageId: string
  ts: number
  provider: string | null
  model: string | null
  agent: string | null
  inputTokens: number | null
  outputTokens: number | null
  reasoningTokens: number | null
  cacheReadTokens: number | null
  cacheWriteTokens: number | null
  totalTokens: number | null
  cost: number | null
  costCurrency: string | null
  costSource: CostSource
  finishReason: string | null
  hostVersion: string | null
}

export type ToolEvent = {
  kind: "tool"
  id: string
  sessionId: string
  messageId: string
  callId: string | null
  tool: string
  status: string
  startedAt: number | null
  endedAt: number | null
  childSessionId: string | null
  outputLength: number | null
}

export type CommandStartEvent = {
  kind: "command_start"
  id: string
  sessionId: string
  name: string
  argumentsLength: number | null
  subtask: boolean | null
  userMessageId: string | null
  startedAt: number
}

export type CommandEndEvent = {
  kind: "command_end"
  id: string
  endedAt: number
  endMessageId: string | null
}

export type ContextSource = {
  category: ContextCategory
  source: string
  chars: number
  estTokens: number
  method: string
}

export type ContextCategory =
  | "system"
  | "environment"
  | "instructions"
  | "skills"
  | "tool_definitions"
  | "conversation"
  | "tool_results"
  | "files"

export type RequestEvent = {
  kind: "request"
  id: string
  sessionId: string
  agent: string | null
  provider: string | null
  model: string | null
  ts: number
  pricingKnown: boolean | null
  sources: ContextSource[]
}

export type RequestStepLinkEvent = {
  kind: "request_step"
  requestId: string
  stepId: string
}

export type GitSnapshotEvent = {
  kind: "git"
  sessionId: string
  directory: string | null
  available: boolean
  commit: string | null
  branch: string | null
  dirty: boolean | null
  capturedAt: number
}

export type FingerprintEvent = {
  kind: "fingerprint"
  id: string
  scope: string[]
  fileCount: number
  partial: boolean
  ts: number
}

export type DiagnosticEvent = {
  kind: "diagnostic"
  level: "info" | "warn" | "error"
  code: string
  message: string
  ts: number
}

export type NormalizedEvent =
  | ProjectEvent
  | SessionEvent
  | MessageEvent
  | SyntheticMarkEvent
  | ModelUsageEvent
  | ToolEvent
  | CommandStartEvent
  | CommandEndEvent
  | RequestEvent
  | RequestStepLinkEvent
  | GitSnapshotEvent
  | FingerprintEvent
  | DiagnosticEvent
